name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  delayed_display:
  json_annotation: ^4.8.1
  freezed_annotation:
  bloc:
  flutter_bloc:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  loading_animation_widget: ^1.2.0+4
  horizontal_data_table: ^4.3.1
  dio: ^5.4.0
  intro_slider: ^4.2.1
  scrollable_positioned_list: ^0.3.8
  sliver_tools: ^0.2.12
  intl:
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  bloc_concurrency: ^0.2.3
  auto_size_text: ^3.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.2.0
  flutter_native_splash: ^2.3.10
  flutter_layout_grid: ^2.0.5
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  connectivity: ^3.0.6
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

dev_dependencies:
  freezed:
  build_runner:
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/animations/
    # - assets/svg_weather/
  uses-material-design: true


# Generated by Spider
spider:
  
  generate_tests: true
  
  no_comments: true
  
  export: true
  
  use_part_of: true
  
  use_references_list: false
  
  package: resources
  groups:
    - path: assets/images
      class_name: Images
      types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
    
    - path: assets/animations
      class_name: Animations
      types: [ .json]

    # - path: assets/svg_weather
    #   class_name: SvgPictures
    #   types: [ .svg]
